import { Activity, Brain, Fingerprint, Globe2, ShieldAlert, ShieldCheck } from 'lucide-react'
import { MatrixRow, SignalConflict, TrustScoreRing } from '../components/Visuals'

const percent = (value) => value == null ? 'Unavailable' : `${Math.round(value * 100)}%`
const valueOrUnavailable = (value) => value == null || value === '' ? 'Unavailable' : value

export default function ResultOverview({ result, onDetail, onNewScan }) {
  const domain = result.domain_analysis
  const brand = result.brand_analysis
  const lexical = result.lexical_analysis
  const ml = result.ml_analysis
  return <main className="results-page">
    <div className="result-heading"><div><p className="eyebrow">Scan overview</p><h1>{domain.domain_name}</h1><div className="result-url-row"><p className="result-url">{result.normalized_url}</p><a className="visit-button" href={result.normalized_url} target="_blank" rel="noopener noreferrer">VISIT ↗</a></div></div><button className="outline-button" onClick={onNewScan}>SCAN ANOTHER WEBSITE</button></div>
    <section className="overview-hero"><div className="hero-score-side"><TrustScoreRing score={result.trustshield_score} riskLevel={result.trustshield_risk_level} /></div><div className="intelligence-matrix"><div className="matrix-heading"><span>TRUSTSHIELD INTELLIGENCE MATRIX</span><small>FUSED SIGNAL SYNTHESIS</small></div><MatrixRow icon={ShieldCheck} label="Technical Security" value={`${result.technical_trust_score}%`} detail={result.risk_level} progress={result.technical_trust_score} onClick={() => onDetail('technical')} /><MatrixRow icon={Globe2} label="Domain Intelligence" value={domain.domain_age_days == null ? 'UNKNOWN' : domain.domain_age_days > 365 ? 'ESTABLISHED' : 'NEW'} detail={domain.domain_age_days == null ? 'Age unavailable' : `${domain.domain_age_days} days old`} tone="amber" onClick={() => onDetail('domain')} /><MatrixRow icon={Fingerprint} label="Brand Risk" value={brand.possible_brand_impersonation ? 'POSSIBLE' : 'LOW'} detail={brand.detected_brand ? `${brand.detected_brand} signal` : 'No brand match'} tone={brand.possible_brand_impersonation ? 'amber' : 'green'} progress={brand.possible_brand_impersonation ? 72 : 8} onClick={() => onDetail('brand')} /><MatrixRow icon={Activity} label="Lexical Risk" value={`${lexical.lexical_risk_score}/100`} detail={lexical.lexical_risk_level} tone="amber" progress={lexical.lexical_risk_score} onClick={() => onDetail('lexical')} /><MatrixRow icon={Brain} label="ML Phishing Risk" value={percent(ml.phishing_probability)} detail={valueOrUnavailable(ml.prediction)} tone="red" progress={ml.phishing_probability == null ? 0 : ml.phishing_probability * 100} onClick={() => onDetail('ml')} /><MatrixRow icon={ShieldAlert} label="External Reputation" value={`${result.reputation_analysis.reputation_risk_score}/100`} detail={`${result.reputation_analysis.reputation_level} · ${result.reputation_analysis.reputation_confidence} CONFIDENCE`} tone={result.reputation_analysis.reputation_risk_score >= 35 ? 'red' : 'green'} progress={result.reputation_analysis.reputation_risk_score} onClick={() => onDetail('reputation')} /></div></section>
    <SignalConflict signalConflict={result.signal_conflict || ml.signal_conflict} conflictMessage={result.conflict_message || ml.conflict_message} technical={result.technical_trust_score} phishing={ml.phishing_probability} onOpen={() => onDetail(result.reputation_analysis.threat_sources ? 'reputation' : 'ml')} />
    <div className="section-heading"><div><span className="eyebrow">Signal summary</span><h2>What we found</h2></div><button className="text-button" onClick={() => onDetail('signals')}>VIEW ALL SIGNALS ↗</button></div>
    <section className="overview-lower"><div><div className="section-heading compact"><h2>Positive signals</h2><button className="text-button" onClick={() => onDetail('positive')}>VIEW ALL ↗</button></div>{(result.positive_signals || []).slice(0, 3).map((signal) => <p className="mini-signal positive-line" key={signal}>✓ {signal}</p>)}</div><div><div className="section-heading compact"><h2>Warning signals</h2><button className="text-button" onClick={() => onDetail('warning')}>VIEW ALL ↗</button></div>{(result.warning_signals || []).slice(0, 3).map((signal) => <p className="mini-signal warning-line" key={signal}>! {signal}</p>)}</div></section>
  </main>
}
